### PR TITLE
Bring project to modern day Rust WASM 

### PR DESCRIPTION
**Pull request by alexschrod**
Hey @lpil. 👋 

This regex tester tool of yours is used by a lot of people, but I couldn't help but notice it was just sitting there, sad and dilapidated, and I thought I'd help bring some life back into it!

In the process made some executive decisions that I'd like to run by you before I turn this into a non-draft pull request, so we're on the same page before anything happens. These are the changes I decided to go ahead and make (and of course you can also just look at the commits/file changes if that's more your style):

* I removed build artifacts from the repo. I don't generally think it's a good idea to put "binaries" into a Git repo; they can't be dealt with as deltas by git, and so your repo will grow in size each time by as much as the size of each new artifact. As a replacement for this, I set up a GitHub Actions workflow to automatically build and deploy the artifact as needed. You can see these [actions in... action on my fork](https://github.com/alexschrod/rustexp/actions) as well as [the result of this automatic deployment under my GitHub pages for said fork](https://alexschrod.github.io/rustexp/). (Yes, that is running the most up-to-date version that I've been working on.)
*  Which brings me to my next point. In order for that GH Actions workflow to deploy properly to your site, I'd need to know how you've configured your deployment/GH Pages, or you have to change yours to match mine. The latter is probably more appropriate. While I assume you've set yours to deploy from your `master` branch from under `/docs`, it makes more sense for automatic deployment for it to happen from the `gh-pages` branch at `/`. So that's the approach I recommend you take, should you choose to move forward with this PR.
* I moved away from [`stdweb`](https://crates.io/crates/stdweb), which hasn't seen an update in over 3 years, and over to [`wasm-bindgen`](https://crates.io/crates/wasm-bindgen) and [`web-sys`](https://crates.io/crates/web-sys), both actively maintained and the currently most appropriate crates for Rust/WASM<->JS interop, and replaced [`cargo-web`](https://crates.io/crates/cargo-web), which again, hasn't seen an update in over 3 years, with [`trunk`](https://crates.io/crates/trunk), a modern WASM application bundler that makes working with Rust-for-WASM a breeze.
* I set a fairly aggressive lint policy (see the first ~130 lines of `main.rs`) and fixed anything about the code that was in violation of said lints.
* I updated `regex` to the latest version. Probably my least controversial decision tbh.
* I hid the "Split on newlines?" checkbox because as far as I can tell, it doesn't actually have any logic associated with it.

Well, there you go; if you have any feedback, I'm very open to making adjustments.

While I'm at it, I'll also say that I'm willing to take over stewardship of this project, should you wish not to take on/keep the maintenance burden of the project; I'd even go so far as to take on the hosting burden (I mean, I'd still use GH pages for it, but I'd be willing to use a domain name under my control if you'd like.)

### CODE REVIEW

**Comment by lpil** [comment]
Hey @alexschrod , sorry only just saw this. Looks great!

Was the CNAME file intentionally removed? I think we'd still need that.

**Comment by lpil** [comment]
Oh, it looks like some other commits have since been added to the branch. Shall I undo those?

**Comment by alexschrod** [comment]
Yeah, sorry, with your lack of response, I decided to take things into my own hands, since I'd noticed you'd been fairly active on GitHub for days after I opened this PR, so I thought you weren't interested. I can undo some of that if you're open to it after all. 😄

**Comment by alexschrod** [comment]
As for the CNAME, it should be added during the GH Action run. I can set that up, too.

I was planning for you to move over to the new model of GH pages since it looks like you're on the very old one from back when they could only exist in a /docs folder under master.

**Comment by alexschrod** [comment]
With this new change, I'll fix things up and let you know when it's ready for review again. 😄

**Comment by lpil** [comment]
Wonderful! Thank you very much for all this work, and your thorough write up. Super helpful 💜 

> I'd noticed you'd been fairly active on GitHub for days after I opened this PR, so I thought you weren't interested since you didn't respond. I can undo some of that if you're open to it after all. 😄

Sorry, my inbox is just very busy 😅 

> Removed the phrase "All Rights Reserved" from the copyright statement because it's not true when using a license like the AGPL.

I don't think that this isn't true. "all rights reserved" means the copyright holders have now waived their rights, it does not conflict with a licence which gives others certain rights also, rather AGPL relies upon copyright being held.
Having said that, it doesn't actually do anything any more. One don't need to write that to state that they retain copyright, so no reason to have it really. Cultural habit I suppose :)

**Comment by alexschrod** [comment]
Noice. 😄 Do you mind if I post about this update/upgrade in various places, like the Rust subreddit or the Rust users forum? Or would you like to do so yourself, perhaps?

**Comment by lpil** [comment]
What a cracking idea. Please do go ahead @alexschrod ! I look forward to reading it. :)

**Comment by alexschrod** [comment]
Here we are. :)

https://www.reddit.com/r/rust/comments/12g9q08/the_rust_regular_expression_editor_tester_has/?
https://users.rust-lang.org/t/the-rust-regular-expression-editor-tester-has-been-updated/92207

**Pull request merged**
